version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    environment:
      - IN_CONTAINER: true
    steps:
      - checkout
      - run: go mod vendor
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/artifacts
      - run:
          name: tests
          command: |
            sudo mkdir -p /cfgs/defaults
            sudo mkdir -p /cfgs/dev
            sudo cp test/configuration/defaults/* /cfgs/defaults
            sudo cp test/configuration/dev/* /cfgs/dev
            make test
            mv coverage.html /tmp/artifacts
            mv c.out /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
      - codecov/upload:
          file: /tmp/artifacts/*
